[noto-fonts-all]
[__config__]
oldver = "old_ver.json"

source = 'github'
github = 'notofonts/notofonts.github.io'
use_max_tag = true
prefix = 'noto-monthly-release-'
include_regex = 'noto-monthly-release.*'
