[__config__]
oldver = "old_ver.json"
newver = "new_ver.json"

[noto-fonts-all]
source = 'github'
github = 'notofonts/notofonts.github.io'
use_max_tag = true
prefix = 'noto-monthly-release-'
include_regex = 'noto-monthly-release.*'
