name: "Repo-Add"
description: "Build archlinux repo"
branding:
  icon: user-check
  color: gray-dark
inputs:
  repo_owner:
    description: "GitHub repository owner"
    required: false
    default: ${{ github.repository_owner }}
  repo_full:
    description: "GitHub repository"
    required: false
    default: ${{ github.repository }}
  path:
    description: "Where the artifact exists"
    required: false
    default: ${{ github.workspace }}
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.repo_owner }}
    - ${{ inputs.repo_full }}
    - ${{ inputs.path }}
