name: "Repo Action"
description: "Build archlinux repo"
branding:
  icon: user-check
  color: gray-dark
inputs:
  repo_owner:
    description: "GitHub repository owner"
    required: false
    default: ${{ github.repository_owner }}
  repo_full:
    description: "GitHub repository"
    required: false
    default: ${{ github.repository }}
  path:
    description: "Where the artifact exists"
    required: false
    default: ${{ github.workspace }}
  request:
    description: "Request"
    required: true
    default: ""
  remove_pkgs:
    description: "Packages need to remove from release and repo"
    required: false
    default: ""
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.repo_owner }}
    - ${{ inputs.repo_full }}
    - ${{ inputs.path }}
    - ${{ inputs.request }}
    - ${{ inputs.pkgs }}