name: "Build AUR Package"
description: "Build an ArchLinux package in Docker container"
branding:
  icon: user-check
  color: gray-dark
inputs:
  nvfile:
    description: "nvchecker version files name"
    required: false
    default: "nvchecker.toml"
  changed_files:
    description: "Changed files"
    required: true
  keyfile:
    description: "Nvchecker key file"
    required: false
    default: ""
outputs:
  build_status:
    description: "Build status"
  remove_pkgs:
    description: "Packages need to remove from release and repo"
  matrix:
    description: "Packages need to update matrix"
  oldver_file:
    description: "Old version file(updated)"
  remove_status:
    description: "Remove status"
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.nvfile }}
    - ${{ inputs.changed_files }}
