name: Build and release
on:
  workflow_dispatch:
  push:
  schedule:
    - cron: "0 */12 * * *"

jobs:
  Build:
    if: ${{ github.ref == 'refs/heads/master' && !contains(github.event.head_commit.message, '[no build]') }}
    permissions: write-all
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        pkgs:
          - adobe-source-han-sans-otc-fonts
          - adobe-source-han-serif-otc-fonts
          - noto-fonts-all
          - clash-meta-alpha-git
          - dae-git
          - dae-rules-dat
          - ctex-windows-fonts
          - wine-patch
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - uses: ./build-aur-action
        id: build
        with:
          pkg_name: ${{ matrix.pkgs }}
          repo_full: ${{ github.repository }}
        env:
          GH_TOKEN: ${{ github.token }}
      - uses: EndBug/add-and-commit@v9
        with:
          add: "${{ matrix.pkgs }}/PKGBUILD"
          message: ${{ matrix.pkgs }}:auto updated to ${{ steps.build.outputs.new_ver }}
          pull: "--rebase --autostash"
      - name: generate tag
        id: tag
        run: |
          count=$(git rev-list --count HEAD)
          hash=$(git rev-parse --short HEAD)
          echo "tag=r${count}.${hash}" >> $GITHUB_OUTPUT
      - name: Upload Packages Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.pkgs }}-${{ steps.tag.outputs.tag }}
          path: ${{ matrix.pkgs }}/${{ steps.build.outputs.asset }}
      - uses: ./delete-asset-action
        if: steps.build.outputs.status == 'true'
        with:
          pkg_name: ${{ matrix.pkgs }}
          repo_full: ${{ github.repository }}
          tag: packages
        env:
          GH_TOKEN: ${{ github.token }}
  Release:
    needs: Build
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          path: bin
      - uses: ./repo-add-action
        with:
          repo_owner: ${{ github.repository_owner }}
          path: bin
      - name: Upload Release
        if: ${{ github.ref == 'refs/heads/master' && !contains(github.event.head_commit.message, '[no rel]') }}
        uses: softprops/action-gh-release@v1
        with:
          tag_name: packages
          files: |
            ${{ github.workspace }}/*.pkg.tar.*
            ${{ github.workspace }}/*.files*
            ${{ github.workspace }}/*.db*
          generate_release_notes: true
      - name: Send notify to telegram
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          format: markdown
          message: "From ${{ github.repository }} - ${{ github.workflow }}: \n Packages build success!\n[View it On Github](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})\n"
