name: Build and release
on:
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout to repository
        uses: actions/checkout@v4
      - name: echo token
        run: echo ${{ secrets.GITHUB_TOKEN }}
